version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    restart: unless-stopped

  data-visualizer:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  db-data:
    driver: local